import {
  Store,
  Product,
  Order,
  Campaign,
  Expense,
  Customer,
  AIInsight,
  CustomerTicket,
  ListingItem,
  CalculationRecord,
} from '../types';

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-us',
    name: 'USA Store',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    isConnected: true,
    apiStatus: 'active',
    totalRevenue: 12430.8,
    totalOrders: 412,
    netProfit: 6580.4,
    margin: 52.9,
    growth: 18.6,
    lastSyncTime: 'Just now',
    accountRole: 'Owner',
  },
  {
    id: 'store-uk',
    name: 'UK Store',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    isConnected: true,
    apiStatus: 'active',
    totalRevenue: 7230.2,
    totalOrders: 238,
    netProfit: 3740.1,
    margin: 51.7,
    growth: 11.3,
    lastSyncTime: '2 mins ago',
    accountRole: 'Owner',
  },
  {
    id: 'store-de',
    name: 'Germany Store',
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    currency: 'EUR',
    currencySymbol: '€',
    isConnected: true,
    apiStatus: 'active',
    totalRevenue: 4520.1,
    totalOrders: 146,
    netProfit: 2310.8,
    margin: 51.1,
    growth: 15.7,
    lastSyncTime: '5 mins ago',
    accountRole: 'Manager',
  },
  {
    id: 'store-ca',
    name: 'Canada Store',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'CA$',
    isConnected: true,
    apiStatus: 'active',
    totalRevenue: 1249.7,
    totalOrders: 44,
    netProfit: 598.9,
    margin: 47.9,
    growth: 7.2,
    lastSyncTime: '12 mins ago',
    accountRole: 'Staff',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Portable Blender',
    sku: 'RUSH-BLD-01',
    image:
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=150&auto=format&fit=crop&q=80',
    category: 'Kitchen & Wellness',
    storeId: 'store-us',
    unitsSold: 142,
    revenue: 4245.8,
    cogs: 1136.0,
    shippingCost: 426.0,
    tiktokFees: 212.29,
    affiliateCommission: 241.11,
    adCost: 800.2,
    totalCost: 2815.6,
    netProfit: 2230.4,
    margin: 52.5,
    stock: 480,
    status: 'star',
  },
  {
    id: 'prod-2',
    title: 'Vacuum Cleaner',
    sku: 'RUSH-VAC-09',
    image:
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=150&auto=format&fit=crop&q=80',
    category: 'Home Cleaning',
    storeId: 'store-us',
    unitsSold: 88,
    revenue: 5271.2,
    cogs: 1760.0,
    shippingCost: 528.0,
    tiktokFees: 263.56,
    affiliateCommission: 310.0,
    adCost: 539.44,
    totalCost: 3401.0,
    netProfit: 1870.2,
    margin: 35.5,
    stock: 210,
    status: 'profitable',
  },
  {
    id: 'prod-3',
    title: 'LED Strip Lights',
    sku: 'RUSH-LED-RGB',
    image:
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=150&auto=format&fit=crop&q=80',
    category: 'Room Decor',
    storeId: 'store-uk',
    unitsSold: 195,
    revenue: 2925.0,
    cogs: 682.5,
    shippingCost: 390.0,
    tiktokFees: 146.25,
    affiliateCommission: 175.5,
    adCost: 110.45,
    totalCost: 1504.7,
    netProfit: 1420.3,
    margin: 48.6,
    stock: 890,
    status: 'scale',
  },
  {
    id: 'prod-4',
    title: 'Air Fryer',
    sku: 'RUSH-FRY-5L',
    image:
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=150&auto=format&fit=crop&q=80',
    category: 'Kitchen Appliances',
    storeId: 'store-de',
    unitsSold: 45,
    revenue: 3595.5,
    cogs: 1350.0,
    shippingCost: 450.0,
    tiktokFees: 179.78,
    affiliateCommission: 215.73,
    adCost: 189.11,
    totalCost: 2384.62,
    netProfit: 1210.88,
    margin: 33.7,
    stock: 140,
    status: 'profitable',
  },
  {
    id: 'prod-5',
    title: 'Phone Holder',
    sku: 'RUSH-HLD-MAG',
    image:
      'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=150&auto=format&fit=crop&q=80',
    category: 'Car & Mobile',
    storeId: 'store-us',
    unitsSold: 210,
    revenue: 2520.0,
    cogs: 630.0,
    shippingCost: 420.0,
    tiktokFees: 126.0,
    affiliateCommission: 150.0,
    adCost: 213.5,
    totalCost: 1539.5,
    netProfit: 980.5,
    margin: 38.9,
    stock: 650,
    status: 'profitable',
  },
  {
    id: 'prod-6',
    title: 'Electric Scalp Massager',
    sku: 'RUSH-SCP-02',
    image:
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=150&auto=format&fit=crop&q=80',
    category: 'Beauty & Wellness',
    storeId: 'store-ca',
    unitsSold: 64,
    revenue: 1536.0,
    cogs: 448.0,
    shippingCost: 192.0,
    tiktokFees: 76.8,
    affiliateCommission: 92.16,
    adCost: 290.4,
    totalCost: 1099.36,
    netProfit: 436.64,
    margin: 28.4,
    stock: 310,
    status: 'profitable',
  },
  {
    id: 'prod-7',
    title: 'Crystal Sunset Lamp',
    sku: 'RUSH-SUN-01',
    image:
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=150&auto=format&fit=crop&q=80',
    category: 'Room Decor',
    storeId: 'store-uk',
    unitsSold: 96,
    revenue: 1910.4,
    cogs: 576.0,
    shippingCost: 288.0,
    tiktokFees: 95.52,
    affiliateCommission: 114.62,
    adCost: 480.0,
    totalCost: 1554.14,
    netProfit: 356.26,
    margin: 18.6,
    stock: 120,
    status: 'bleeding',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: '#O-24578',
    customerName: 'Alex Johnson',
    customerEmail: 'alex.j@gmail.com',
    storeId: 'store-us',
    storeName: 'USA Store',
    storeFlag: '🇺🇸',
    date: 'May 23, 2024 15:42',
    items: [
      {
        productId: 'prod-1',
        productTitle: 'Portable Blender',
        sku: 'RUSH-BLD-01',
        quantity: 1,
        price: 38.9,
      },
    ],
    totalAmount: 38.9,
    cogs: 8.0,
    fees: 3.5,
    shipping: 4.2,
    netProfit: 23.2,
    status: 'Completed',
    trackingNumber: 'USPS9400111899562230',
    carrier: 'USPS Priority',
  },
  {
    id: 'ord-2',
    orderNumber: '#O-24577',
    customerName: 'Emily Davis',
    customerEmail: 'emily.davis@hotmail.co.uk',
    storeId: 'store-uk',
    storeName: 'UK Store',
    storeFlag: '🇬🇧',
    date: 'May 23, 2024 15:10',
    items: [
      {
        productId: 'prod-3',
        productTitle: 'LED Strip Lights',
        sku: 'RUSH-LED-RGB',
        quantity: 2,
        price: 29.5,
      },
    ],
    totalAmount: 29.5,
    cogs: 7.0,
    fees: 2.65,
    shipping: 3.85,
    netProfit: 16.0,
    status: 'Completed',
    trackingNumber: 'RM893201481GB',
    carrier: 'Royal Mail Tracked 24',
  },
  {
    id: 'ord-3',
    orderNumber: '#O-24576',
    customerName: 'Michael Brown',
    customerEmail: 'm.brown@web.de',
    storeId: 'store-de',
    storeName: 'Germany Store',
    storeFlag: '🇩🇪',
    date: 'May 23, 2024 14:48',
    items: [
      {
        productId: 'prod-4',
        productTitle: 'Air Fryer',
        sku: 'RUSH-FRY-5L',
        quantity: 1,
        price: 45.2,
      },
    ],
    totalAmount: 45.2,
    cogs: 18.0,
    fees: 4.1,
    shipping: 5.5,
    netProfit: 17.6,
    status: 'Processing',
    trackingNumber: 'DHL00340434281923',
    carrier: 'DHL Paket',
  },
  {
    id: 'ord-4',
    orderNumber: '#O-24575',
    customerName: 'Sophia Wilson',
    customerEmail: 'sophia.w@rogers.ca',
    storeId: 'store-ca',
    storeName: 'Canada Store',
    storeFlag: '🇨🇦',
    date: 'May 23, 2024 14:15',
    items: [
      {
        productId: 'prod-5',
        productTitle: 'Phone Holder',
        sku: 'RUSH-HLD-MAG',
        quantity: 1,
        price: 22.1,
      },
    ],
    totalAmount: 22.1,
    cogs: 3.0,
    fees: 2.0,
    shipping: 4.1,
    netProfit: 13.0,
    status: 'Completed',
    trackingNumber: 'CP784912093CA',
    carrier: 'Canada Post Expedited',
  },
  {
    id: 'ord-5',
    orderNumber: '#O-24574',
    customerName: 'Daniel Lee',
    customerEmail: 'danlee@outlook.com',
    storeId: 'store-us',
    storeName: 'USA Store',
    storeFlag: '🇺🇸',
    date: 'May 23, 2024 13:55',
    items: [
      {
        productId: 'prod-1',
        productTitle: 'Portable Blender',
        sku: 'RUSH-BLD-01',
        quantity: 1,
        price: 31.8,
      },
    ],
    totalAmount: 31.8,
    cogs: 8.0,
    fees: 2.85,
    shipping: 4.2,
    netProfit: 16.75,
    status: 'Completed',
    trackingNumber: 'USPS9400111899562231',
    carrier: 'USPS Priority',
  },
  {
    id: 'ord-6',
    orderNumber: '#O-24573',
    customerName: 'Chloe Bennett',
    customerEmail: 'chloeb@gmail.com',
    storeId: 'store-us',
    storeName: 'USA Store',
    storeFlag: '🇺🇸',
    date: 'May 23, 2024 12:20',
    items: [
      {
        productId: 'prod-2',
        productTitle: 'Vacuum Cleaner',
        sku: 'RUSH-VAC-09',
        quantity: 1,
        price: 59.9,
      },
    ],
    totalAmount: 59.9,
    cogs: 20.0,
    fees: 5.4,
    shipping: 6.0,
    netProfit: 28.5,
    status: 'Completed',
    trackingNumber: 'UPS1Z9999999999999999',
    carrier: 'UPS Ground',
  },
  {
    id: 'ord-7',
    orderNumber: '#O-24572',
    customerName: 'Oliver Smith',
    customerEmail: 'oliver.smith@yahoo.co.uk',
    storeId: 'store-uk',
    storeName: 'UK Store',
    storeFlag: '🇬🇧',
    date: 'May 23, 2024 11:45',
    items: [
      {
        productId: 'prod-7',
        productTitle: 'Crystal Sunset Lamp',
        sku: 'RUSH-SUN-01',
        quantity: 1,
        price: 19.9,
      },
    ],
    totalAmount: 19.9,
    cogs: 6.0,
    fees: 1.8,
    shipping: 3.5,
    netProfit: 8.6,
    status: 'Processing',
    trackingNumber: 'RM893201482GB',
    carrier: 'Royal Mail Tracked 48',
  },
  {
    id: 'ord-8',
    orderNumber: '#O-24571',
    customerName: 'Hannah Mueller',
    customerEmail: 'hannah.m@gmx.de',
    storeId: 'store-de',
    storeName: 'Germany Store',
    storeFlag: '🇩🇪',
    date: 'May 23, 2024 10:30',
    items: [
      {
        productId: 'prod-6',
        productTitle: 'Electric Scalp Massager',
        sku: 'RUSH-SCP-02',
        quantity: 1,
        price: 24.0,
      },
    ],
    totalAmount: 24.0,
    cogs: 7.0,
    fees: 2.15,
    shipping: 4.0,
    netProfit: 10.85,
    status: 'Canceled',
    trackingNumber: '-',
    carrier: '-',
  },
  {
    id: 'ord-9',
    orderNumber: '#O-24570',
    customerName: 'Lucas Dubois',
    customerEmail: 'lucas.d@bell.net',
    storeId: 'store-ca',
    storeName: 'Canada Store',
    storeFlag: '🇨🇦',
    date: 'May 23, 2024 09:12',
    items: [
      {
        productId: 'prod-1',
        productTitle: 'Portable Blender',
        sku: 'RUSH-BLD-01',
        quantity: 1,
        price: 34.5,
      },
    ],
    totalAmount: 34.5,
    cogs: 8.0,
    fees: 3.1,
    shipping: 4.5,
    netProfit: -34.5,
    status: 'Refunded',
    trackingNumber: 'CP784912094CA',
    carrier: 'Canada Post',
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Summer Sale',
    storeId: 'store-us',
    storeName: 'USA Store',
    status: 'Active',
    spend: 800.2,
    revenue: 3450.6,
    roas: 4.31,
    cpa: 12.45,
    impressions: 482000,
    clicks: 14200,
    ctr: 2.95,
    purchases: 64,
    profit: 1250.3,
    trend: 'up',
  },
  {
    id: 'camp-2',
    name: 'Flash Deal',
    storeId: 'store-us',
    storeName: 'USA Store',
    status: 'Active',
    spend: 620.4,
    revenue: 2180.2,
    roas: 3.51,
    cpa: 11.2,
    impressions: 340000,
    clicks: 10800,
    ctr: 3.18,
    purchases: 55,
    profit: 780.4,
    trend: 'up',
  },
  {
    id: 'camp-3',
    name: 'New Launch',
    storeId: 'store-uk',
    storeName: 'UK Store',
    status: 'Active',
    spend: 450.6,
    revenue: 1320.4,
    roas: 2.93,
    cpa: 10.15,
    impressions: 215000,
    clicks: 6900,
    ctr: 3.21,
    purchases: 44,
    profit: 420.1,
    trend: 'stable',
  },
  {
    id: 'camp-4',
    name: 'Retargeting',
    storeId: 'store-us',
    storeName: 'USA Store',
    status: 'Active',
    spend: 300.3,
    revenue: 950.3,
    roas: 3.16,
    cpa: 9.2,
    impressions: 128000,
    clicks: 5100,
    ctr: 3.98,
    purchases: 32,
    profit: 310.2,
    trend: 'up',
  },
  {
    id: 'camp-5',
    name: 'Video Boost',
    storeId: 'store-de',
    storeName: 'Germany Store',
    status: 'Active',
    spend: 169.0,
    revenue: 420.5,
    roas: 2.62,
    cpa: 8.4,
    impressions: 89000,
    clicks: 2900,
    ctr: 3.26,
    purchases: 20,
    profit: 110.4,
    trend: 'down',
  },
  {
    id: 'camp-6',
    name: 'Sunset Lamp Broad Test',
    storeId: 'store-uk',
    storeName: 'UK Store',
    status: 'Paused',
    spend: 210.0,
    revenue: 260.0,
    roas: 1.24,
    cpa: 26.25,
    impressions: 95000,
    clicks: 1800,
    ctr: 1.89,
    purchases: 8,
    profit: -110.0,
    trend: 'down',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    title: 'TikTok Shop SaaS Suite & Automations',
    category: 'Software',
    amount: 199.0,
    recurrence: 'Monthly',
    storeId: 'all',
    storeName: 'All Stores',
    date: '2024-05-01',
    status: 'Paid',
  },
  {
    id: 'exp-2',
    title: 'Virtual Assistant & TikTok Customer Rep (2 Staff)',
    category: 'Staff',
    amount: 1200.0,
    recurrence: 'Monthly',
    storeId: 'all',
    storeName: 'All Stores',
    date: '2024-05-05',
    status: 'Paid',
  },
  {
    id: 'exp-3',
    title: '3PL Fulfillment Warehouse Storage & Pick-Pack',
    category: 'Warehouse',
    amount: 850.0,
    recurrence: 'Monthly',
    storeId: 'store-us',
    storeName: 'USA Store',
    date: '2024-05-10',
    status: 'Paid',
  },
  {
    id: 'exp-4',
    title: 'TikTok Influencer Samples & Seed Packages (25 units)',
    category: 'Marketing',
    amount: 375.0,
    recurrence: 'One-off',
    storeId: 'store-uk',
    storeName: 'UK Store',
    date: '2024-05-14',
    status: 'Paid',
  },
  {
    id: 'exp-5',
    title: 'Custom Eco Branded Packaging & Poly Mailers',
    category: 'Packaging',
    amount: 450.0,
    recurrence: 'One-off',
    storeId: 'all',
    storeName: 'All Stores',
    date: '2024-05-18',
    status: 'Paid',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Alex Johnson',
    email: 'alex.j@gmail.com',
    country: 'United States',
    totalOrders: 4,
    totalSpent: 168.4,
    netProfit: 98.2,
    cac: 12.45,
    ltv: 168.4,
    lastOrderDate: 'May 23, 2024',
    tier: 'VIP',
  },
  {
    id: 'cust-2',
    name: 'Emily Davis',
    email: 'emily.davis@hotmail.co.uk',
    country: 'United Kingdom',
    totalOrders: 3,
    totalSpent: 114.2,
    netProfit: 66.8,
    cac: 10.15,
    ltv: 114.2,
    lastOrderDate: 'May 23, 2024',
    tier: 'Loyal',
  },
  {
    id: 'cust-3',
    name: 'Michael Brown',
    email: 'm.brown@web.de',
    country: 'Germany',
    totalOrders: 2,
    totalSpent: 88.5,
    netProfit: 41.2,
    cac: 8.4,
    ltv: 88.5,
    lastOrderDate: 'May 23, 2024',
    tier: 'Loyal',
  },
  {
    id: 'cust-4',
    name: 'Sophia Wilson',
    email: 'sophia.w@rogers.ca',
    country: 'Canada',
    totalOrders: 1,
    totalSpent: 22.1,
    netProfit: 13.0,
    cac: 9.2,
    ltv: 22.1,
    lastOrderDate: 'May 23, 2024',
    tier: 'New',
  },
  {
    id: 'cust-5',
    name: 'Chloe Bennett',
    email: 'chloeb@gmail.com',
    country: 'United States',
    totalOrders: 5,
    totalSpent: 245.9,
    netProfit: 142.3,
    cac: 11.2,
    ltv: 245.9,
    lastOrderDate: 'May 23, 2024',
    tier: 'VIP',
  },
];

export const INITIAL_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ins-1',
    type: 'win',
    text: 'Your profit increased by 20.4% compared to last week.',
    detail: 'Revenue grew $3,980.20 while maintaining ad spend efficiency at 3.82x blended ROAS.',
    badge: '+20.4% Net Growth',
  },
  {
    id: 'ins-2',
    type: 'star',
    text: 'Portable Blender is your most profitable product.',
    detail: 'Generated $2,230.40 net profit with a 52.5% margin across USA & UK stores.',
    badge: 'Star Product',
  },
  {
    id: 'ins-3',
    type: 'warning',
    text: "Campaign 'Summer Sale' has high spend but low profit.",
    detail:
      'Ad CPA rose to $12.45 on broad target. Recommend narrowing to TikTok Engaged Shoppers.',
    badge: 'Action Needed',
  },
  {
    id: 'ins-4',
    type: 'scale',
    text: 'Consider scaling products with margin > 40%.',
    detail: 'LED Strip Lights and Phone Holder have low ad saturation and >45% profit margins.',
    badge: 'Scale Opportunity',
  },
];

export const INITIAL_TICKETS: CustomerTicket[] = [
  {
    id: 'tkt-1',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.j@icloud.com',
    orderNumber: '#O-24560',
    storeName: 'USA Store',
    subject: 'Where is my order? Ordered 3 days ago',
    category: 'Order Status',
    status: 'Pending AI' as CustomerTicket['status'],
    priority: 'High',
    messages: [
      {
        id: 'msg-1',
        sender: 'customer',
        senderName: 'Sarah Jenkins',
        text: 'Hi, I ordered the portable blender 3 days ago. Can you tell me when it will arrive?',
        timestamp: '10 mins ago',
      },
    ],
    suggestedAiReply:
      'Hi Sarah! 👋 Thanks for reaching out. Your order #O-24560 (Portable Blender) was shipped via USPS Priority with tracking number USPS9400111899562230. It is currently in transit and scheduled to arrive on Monday, May 27th. You can track live updates here: https://tools.usps.com. Let us know if you need anything else!',
  },
  {
    id: 'tkt-2',
    customerName: 'David Clark',
    customerEmail: 'david.c@gmail.com',
    orderNumber: '#O-24545',
    storeName: 'UK Store',
    subject: 'How do I clean the portable blender blades safely?',
    category: 'Product Question',
    status: 'AI Responded',
    priority: 'Medium',
    messages: [
      {
        id: 'msg-2',
        sender: 'customer',
        senderName: 'David Clark',
        text: 'Hello, what is the best way to clean the blender without damaging the motor base?',
        timestamp: '2 hours ago',
      },
      {
        id: 'msg-3',
        sender: 'ai',
        senderName: 'Rush AI Assistant',
        text: 'Hi David! ✨ For effortless and safe cleaning: Simply fill the blender halfway with warm water, add a drop of dish soap, secure the lid, and double-press the power button to self-clean for 30 seconds. Rinse thoroughly. The motor base is IPX7 waterproof, but please do not submerge it in boiling water. Happy blending!',
        timestamp: '2 hours ago',
      },
    ],
    suggestedAiReply: '',
  },
  {
    id: 'tkt-3',
    customerName: 'Emma Watson',
    customerEmail: 'emma.w@yahoo.com',
    orderNumber: '#O-24522',
    storeName: 'USA Store',
    subject: 'Item arrived with a broken charging cable',
    category: 'Defect / Damage',
    status: 'Escalated',
    priority: 'High',
    messages: [
      {
        id: 'msg-4',
        sender: 'customer',
        senderName: 'Emma Watson',
        text: 'Hi there, I received my LED lights today but the USB power cable is bent and not turning on. Can I get a replacement?',
        timestamp: '4 hours ago',
      },
      {
        id: 'msg-5',
        sender: 'agent',
        senderName: 'Support Lead (John)',
        text: 'Hi Emma, we are so sorry about that! A replacement USB power adapter and controller has been dispatched today free of charge. Tracking number: USPS9400111899569999.',
        timestamp: '3 hours ago',
      },
    ],
    suggestedAiReply: '',
  },
];

export const PROFIT_TREND_DATA = [
  { date: 'May 17', profit: 1650, revenue: 3200, expenses: 1550 },
  { date: 'May 18', profit: 1980, revenue: 3850, expenses: 1870 },
  { date: 'May 19', profit: 1420, revenue: 2900, expenses: 1480 },
  { date: 'May 20', profit: 2250, revenue: 4300, expenses: 2050 },
  { date: 'May 21', profit: 2680, revenue: 4900, expenses: 2220 },
  { date: 'May 22', profit: 1850, revenue: 3650, expenses: 1800 },
  { date: 'May 23', profit: 1400.2, revenue: 2630.8, expenses: 1230.6 },
];

export const INITIAL_LISTINGS: ListingItem[] = [
  {
    id: 'list-1',
    productName: 'Portable Fresh Juice Blender 450ml',
    sku: 'RUSH-BLD-01',
    category: 'Kitchen & Health',
    sellingPrice: 38.9,
    stock: 240,
    status: 'synced',
    createdAt: '2026-08-22',
    syncedAt: '2026-08-24 14:30',
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=150',
    bulletPoints: [
      '6 Stainless Steel 3D Blades for instant smooth crushing in 30 seconds',
      'USB-C Rechargeable with 2400mAh battery (up to 15 blends per full charge)',
      'BPA-Free Food Grade PCTG material with waterproof magnetic induction safety',
    ],
    viralHooks: [
      'Stop buying $8 smoothies when this exists...',
      'My gym trainer told me about this portable hack!',
    ],
    tags: ['#portableblender', '#tiktokshopfinds', '#smoothierecipe', '#fitnesshack'],
  },
  {
    id: 'list-2',
    productName: 'RGB LED Smart Hexagon Wall Panels (10-Pack)',
    sku: 'RUSH-LED-01',
    category: 'Home & Room Decor',
    sellingPrice: 49.99,
    stock: 180,
    status: 'ready',
    createdAt: '2026-08-23',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=150',
    bulletPoints: [
      'Music Sync Mode with built-in mic reacts dynamically to game sound & bass',
      'Modular puzzle connector allows endless custom room geometric designs',
      '16 Million RGB Colors controllable via Smart App & Wireless Remote',
    ],
    viralHooks: [
      'Room transformation under $50 you need to see...',
      'Gamers, your setup is not complete without this.',
    ],
    tags: ['#roomdecor', '#gamingsetup', '#ledlights', '#tiktokfinds'],
  },
  {
    id: 'list-3',
    productName: 'Deep Hydrating Hyaluronic Face Serum 30ml',
    sku: 'RUSH-SRM-01',
    category: 'Beauty & Skincare',
    sellingPrice: 28.5,
    stock: 450,
    status: 'synced',
    createdAt: '2026-08-21',
    syncedAt: '2026-08-23 09:15',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=150',
    bulletPoints: [
      'Triple Molecular Weight Formula hydrates deep dermal barriers instantly',
      'Non-greasy, fast-absorbing with organic Green Tea and Niacinamide',
      'Cruelty-Free, Dermatologist Approved, fragrance-free for sensitive skin',
    ],
    viralHooks: [
      'Glass skin in 7 days without spending $100...',
      'Why dermatologists on TikTok are obsessing over this serum!',
    ],
    tags: ['#glassskin', '#skincareroutine', '#faceserum', '#glowup'],
  },
  {
    id: 'list-4',
    productName: 'Wireless Noise Canceling Earbuds Pro',
    sku: 'RUSH-EAR-01',
    category: 'Electronics',
    sellingPrice: 42.0,
    stock: 95,
    status: 'draft',
    createdAt: '2026-08-24',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=150',
    bulletPoints: [
      'Active Noise Cancellation (ANC) up to 35dB blocks ambient room noise',
      'Ultra-low 45ms gaming latency with Bluetooth 5.3 connection stability',
      '36-Hour playback with pocket charging case and IPX5 sweat resistance',
    ],
    viralHooks: [
      'Are these $40 earbuds actually better than AirPods Pro?',
    ],
    tags: ['#earbuds', '#techreview', '#noisecancelling', '#tiktokmademebuyit'],
  },
];

export const INITIAL_CALCULATION_HISTORY: CalculationRecord[] = [
  {
    id: 'calc-1',
    name: 'Portable Fresh Juice Blender',
    sku: 'RUSH-BLD-01',
    category: 'Kitchen & Health',
    sellingPrice: 38.9,
    cogs: 8.0,
    shippingCost: 4.2,
    packagingCost: 0.9,
    tiktokFeePercent: 5.0,
    affiliatePercent: 10.0,
    adCpa: 6.5,
    otherExpenses: 0.4,
    netProfit: 13.88,
    profitMarginPercent: 35.7,
    breakEvenPrice: 22.4,
    healthStatus: 'excellent',
    createdAt: '2026-08-24 18:20',
    bestFor: 'High Volume Scaling & Creator Spark Ads',
  },
  {
    id: 'calc-2',
    name: 'RGB LED Smart Hexagon Panels',
    sku: 'RUSH-LED-01',
    category: 'Home & Room Decor',
    sellingPrice: 49.99,
    cogs: 11.5,
    shippingCost: 5.8,
    packagingCost: 1.2,
    tiktokFeePercent: 5.0,
    affiliatePercent: 12.0,
    adCpa: 8.0,
    otherExpenses: 0.5,
    netProfit: 14.59,
    profitMarginPercent: 29.2,
    breakEvenPrice: 30.1,
    healthStatus: 'good',
    createdAt: '2026-08-23 11:45',
    bestFor: 'High AOV Bundle Upsells',
  },
  {
    id: 'calc-3',
    name: 'Deep Hydrating Face Serum',
    sku: 'RUSH-SRM-01',
    category: 'Beauty & Skincare',
    sellingPrice: 28.5,
    cogs: 3.8,
    shippingCost: 3.2,
    packagingCost: 0.6,
    tiktokFeePercent: 5.0,
    affiliatePercent: 15.0,
    adCpa: 4.5,
    otherExpenses: 0.3,
    netProfit: 10.43,
    profitMarginPercent: 36.6,
    breakEvenPrice: 14.8,
    healthStatus: 'excellent',
    createdAt: '2026-08-22 15:10',
    bestFor: 'Viral Organic TikTok Creator Seeding',
  },
  {
    id: 'calc-4',
    name: 'Crystal Sunset Lamp Projector',
    sku: 'RUSH-SUN-01',
    category: 'Room Decor',
    sellingPrice: 24.99,
    cogs: 6.2,
    shippingCost: 3.8,
    packagingCost: 0.8,
    tiktokFeePercent: 5.0,
    affiliatePercent: 10.0,
    adCpa: 9.5,
    otherExpenses: 0.4,
    netProfit: 0.62,
    profitMarginPercent: 2.5,
    breakEvenPrice: 24.1,
    healthStatus: 'low',
    createdAt: '2026-08-21 09:30',
    bestFor: 'Price Optimization Needed',
  },
];

