import { Store, Product, Order, Campaign, Expense, Customer, AIInsight, CustomerTicket } from '../types';

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-us',
    name: 'USA Store',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    isConnected: true,
    apiStatus: 'active',
    totalRevenue: 12430.80,
    totalOrders: 412,
    netProfit: 6580.40,
    margin: 52.9,
    growth: 18.6,
    lastSyncTime: 'Just now',
    accountRole: 'Owner',
  },
  {
    id: 'store-uk',
    name: 'UK Store',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    isConnected: true,
    apiStatus: 'active',
    totalRevenue: 7230.20,
    totalOrders: 238,
    netProfit: 3740.10,
    margin: 51.7,
    growth: 11.3,
    lastSyncTime: '2 mins ago',
    accountRole: 'Owner',
  },
  {
    id: 'store-de',
    name: 'Germany Store',
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    currency: 'EUR',
    currencySymbol: '€',
    isConnected: true,
    apiStatus: 'active',
    totalRevenue: 4520.10,
    totalOrders: 146,
    netProfit: 2310.80,
    margin: 51.1,
    growth: 15.7,
    lastSyncTime: '5 mins ago',
    accountRole: 'Manager',
  },
  {
    id: 'store-ca',
    name: 'Canada Store',
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'CA$',
    isConnected: true,
    apiStatus: 'active',
    totalRevenue: 1249.70,
    totalOrders: 44,
    netProfit: 598.90,
    margin: 47.9,
    growth: 7.2,
    lastSyncTime: '12 mins ago',
    accountRole: 'Staff',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Portable Blender',
    sku: 'RUSH-BLD-01',
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=150&auto=format&fit=crop&q=80',
    category: 'Kitchen & Wellness',
    storeId: 'store-us',
    unitsSold: 142,
    revenue: 4245.80,
    cogs: 1136.00,
    shippingCost: 426.00,
    tiktokFees: 212.29,
    affiliateCommission: 241.11,
    adCost: 800.20,
    totalCost: 2815.60,
    netProfit: 2230.40,
    margin: 52.5,
    stock: 480,
    status: 'star',
  },
  {
    id: 'prod-2',
    title: 'Vacuum Cleaner',
    sku: 'RUSH-VAC-09',
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=150&auto=format&fit=crop&q=80',
    category: 'Home Cleaning',
    storeId: 'store-us',
    unitsSold: 88,
    revenue: 5271.20,
    cogs: 1760.00,
    shippingCost: 528.00,
    tiktokFees: 263.56,
    affiliateCommission: 310.00,
    adCost: 539.44,
    totalCost: 3401.00,
    netProfit: 1870.20,
    margin: 35.5,
    stock: 210,
    status: 'profitable',
  },
  {
    id: 'prod-3',
    title: 'LED Strip Lights',
    sku: 'RUSH-LED-RGB',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=150&auto=format&fit=crop&q=80',
    category: 'Room Decor',
    storeId: 'store-uk',
    unitsSold: 195,
    revenue: 2925.00,
    cogs: 682.50,
    shippingCost: 390.00,
    tiktokFees: 146.25,
    affiliateCommission: 175.50,
    adCost: 110.45,
    totalCost: 1504.70,
    netProfit: 1420.30,
    margin: 48.6,
    stock: 890,
    status: 'scale',
  },
  {
    id: 'prod-4',
    title: 'Air Fryer',
    sku: 'RUSH-FRY-5L',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=150&auto=format&fit=crop&q=80',
    category: 'Kitchen Appliances',
    storeId: 'store-de',
    unitsSold: 45,
    revenue: 3595.50,
    cogs: 1350.00,
    shippingCost: 450.00,
    tiktokFees: 179.78,
    affiliateCommission: 215.73,
    adCost: 189.11,
    totalCost: 2384.62,
    netProfit: 1210.88,
    margin: 33.7,
    stock: 140,
    status: 'profitable',
  },
  {
    id: 'prod-5',
    title: 'Phone Holder',
    sku: 'RUSH-HLD-MAG',
    image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=150&auto=format&fit=crop&q=80',
    category: 'Car & Mobile',
    storeId: 'store-us',
    unitsSold: 210,
    revenue: 2520.00,
    cogs: 630.00,
    shippingCost: 420.00,
    tiktokFees: 126.00,
    affiliateCommission: 150.00,
    adCost: 213.50,
    totalCost: 1539.50,
    netProfit: 980.50,
    margin: 38.9,
    stock: 650,
    status: 'profitable',
  },
  {
    id: 'prod-6',
    title: 'Electric Scalp Massager',
    sku: 'RUSH-SCP-02',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=150&auto=format&fit=crop&q=80',
    category: 'Beauty & Wellness',
    storeId: 'store-ca',
    unitsSold: 64,
    revenue: 1536.00,
    cogs: 448.00,
    shippingCost: 192.00,
    tiktokFees: 76.80,
    affiliateCommission: 92.16,
    adCost: 290.40,
    totalCost: 1099.36,
    netProfit: 436.64,
    margin: 28.4,
    stock: 310,
    status: 'profitable',
  },
  {
    id: 'prod-7',
    title: 'Crystal Sunset Lamp',
    sku: 'RUSH-SUN-01',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=150&auto=format&fit=crop&q=80',
    category: 'Room Decor',
    storeId: 'store-uk',
    unitsSold: 96,
    revenue: 1910.40,
    cogs: 576.00,
    shippingCost: 288.00,
    tiktokFees: 95.52,
    affiliateCommission: 114.62,
    adCost: 480.00,
    totalCost: 1554.14,
    netProfit: 356.26,
    margin: 18.6,
    stock: 120,
    status: 'bleeding',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: '#O-24578',
    customerName: 'Alex Johnson',
    customerEmail: 'alex.j@gmail.com',
    storeId: 'store-us',
    storeName: 'USA Store',
    storeFlag: '🇺🇸',
    date: 'May 23, 2024 15:42',
    items: [{ productId: 'prod-1', productTitle: 'Portable Blender', sku: 'RUSH-BLD-01', quantity: 1, price: 38.90 }],
    totalAmount: 38.90,
    cogs: 8.00,
    fees: 3.50,
    shipping: 4.20,
    netProfit: 23.20,
    status: 'Completed',
    trackingNumber: 'USPS9400111899562230',
    carrier: 'USPS Priority',
  },
  {
    id: 'ord-2',
    orderNumber: '#O-24577',
    customerName: 'Emily Davis',
    customerEmail: 'emily.davis@hotmail.co.uk',
    storeId: 'store-uk',
    storeName: 'UK Store',
    storeFlag: '🇬🇧',
    date: 'May 23, 2024 15:10',
    items: [{ productId: 'prod-3', productTitle: 'LED Strip Lights', sku: 'RUSH-LED-RGB', quantity: 2, price: 29.50 }],
    totalAmount: 29.50,
    cogs: 7.00,
    fees: 2.65,
    shipping: 3.85,
    netProfit: 16.00,
    status: 'Completed',
    trackingNumber: 'RM893201481GB',
    carrier: 'Royal Mail Tracked 24',
  },
  {
    id: 'ord-3',
    orderNumber: '#O-24576',
    customerName: 'Michael Brown',
    customerEmail: 'm.brown@web.de',
    storeId: 'store-de',
    storeName: 'Germany Store',
    storeFlag: '🇩🇪',
    date: 'May 23, 2024 14:48',
    items: [{ productId: 'prod-4', productTitle: 'Air Fryer', sku: 'RUSH-FRY-5L', quantity: 1, price: 45.20 }],
    totalAmount: 45.20,
    cogs: 18.00,
    fees: 4.10,
    shipping: 5.50,
    netProfit: 17.60,
    status: 'Processing',
    trackingNumber: 'DHL00340434281923',
    carrier: 'DHL Paket',
  },
  {
    id: 'ord-4',
    orderNumber: '#O-24575',
    customerName: 'Sophia Wilson',
    customerEmail: 'sophia.w@rogers.ca',
    storeId: 'store-ca',
    storeName: 'Canada Store',
    storeFlag: '🇨🇦',
    date: 'May 23, 2024 14:15',
    items: [{ productId: 'prod-5', productTitle: 'Phone Holder', sku: 'RUSH-HLD-MAG', quantity: 1, price: 22.10 }],
    totalAmount: 22.10,
    cogs: 3.00,
    fees: 2.00,
    shipping: 4.10,
    netProfit: 13.00,
    status: 'Completed',
    trackingNumber: 'CP784912093CA',
    carrier: 'Canada Post Expedited',
  },
  {
    id: 'ord-5',
    orderNumber: '#O-24574',
    customerName: 'Daniel Lee',
    customerEmail: 'danlee@outlook.com',
    storeId: 'store-us',
    storeName: 'USA Store',
    storeFlag: '🇺🇸',
    date: 'May 23, 2024 13:55',
    items: [{ productId: 'prod-1', productTitle: 'Portable Blender', sku: 'RUSH-BLD-01', quantity: 1, price: 31.80 }],
    totalAmount: 31.80,
    cogs: 8.00,
    fees: 2.85,
    shipping: 4.20,
    netProfit: 16.75,
    status: 'Completed',
    trackingNumber: 'USPS9400111899562231',
    carrier: 'USPS Priority',
  },
  {
    id: 'ord-6',
    orderNumber: '#O-24573',
    customerName: 'Chloe Bennett',
    customerEmail: 'chloeb@gmail.com',
    storeId: 'store-us',
    storeName: 'USA Store',
    storeFlag: '🇺🇸',
    date: 'May 23, 2024 12:20',
    items: [{ productId: 'prod-2', productTitle: 'Vacuum Cleaner', sku: 'RUSH-VAC-09', quantity: 1, price: 59.90 }],
    totalAmount: 59.90,
    cogs: 20.00,
    fees: 5.40,
    shipping: 6.00,
    netProfit: 28.50,
    status: 'Completed',
    trackingNumber: 'UPS1Z9999999999999999',
    carrier: 'UPS Ground',
  },
  {
    id: 'ord-7',
    orderNumber: '#O-24572',
    customerName: 'Oliver Smith',
    customerEmail: 'oliver.smith@yahoo.co.uk',
    storeId: 'store-uk',
    storeName: 'UK Store',
    storeFlag: '🇬🇧',
    date: 'May 23, 2024 11:45',
    items: [{ productId: 'prod-7', productTitle: 'Crystal Sunset Lamp', sku: 'RUSH-SUN-01', quantity: 1, price: 19.90 }],
    totalAmount: 19.90,
    cogs: 6.00,
    fees: 1.80,
    shipping: 3.50,
    netProfit: 8.60,
    status: 'Processing',
    trackingNumber: 'RM893201482GB',
    carrier: 'Royal Mail Tracked 48',
  },
  {
    id: 'ord-8',
    orderNumber: '#O-24571',
    customerName: 'Hannah Mueller',
    customerEmail: 'hannah.m@gmx.de',
    storeId: 'store-de',
    storeName: 'Germany Store',
    storeFlag: '🇩🇪',
    date: 'May 23, 2024 10:30',
    items: [{ productId: 'prod-6', productTitle: 'Electric Scalp Massager', sku: 'RUSH-SCP-02', quantity: 1, price: 24.00 }],
    totalAmount: 24.00,
    cogs: 7.00,
    fees: 2.15,
    shipping: 4.00,
    netProfit: 10.85,
    status: 'Canceled',
    trackingNumber: '-',
    carrier: '-',
  },
  {
    id: 'ord-9',
    orderNumber: '#O-24570',
    customerName: 'Lucas Dubois',
    customerEmail: 'lucas.d@bell.net',
    storeId: 'store-ca',
    storeName: 'Canada Store',
    storeFlag: '🇨🇦',
    date: 'May 23, 2024 09:12',
    items: [{ productId: 'prod-1', productTitle: 'Portable Blender', sku: 'RUSH-BLD-01', quantity: 1, price: 34.50 }],
    totalAmount: 34.50,
    cogs: 8.00,
    fees: 3.10,
    shipping: 4.50,
    netProfit: -34.50,
    status: 'Refunded',
    trackingNumber: 'CP784912094CA',
    carrier: 'Canada Post',
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Summer Sale',
    storeId: 'store-us',
    storeName: 'USA Store',
    status: 'Active',
    spend: 800.20,
    revenue: 3450.60,
    roas: 4.31,
    cpa: 12.45,
    impressions: 482000,
    clicks: 14200,
    ctr: 2.95,
    purchases: 64,
    profit: 1250.30,
    trend: 'up',
  },
  {
    id: 'camp-2',
    name: 'Flash Deal',
    storeId: 'store-us',
    storeName: 'USA Store',
    status: 'Active',
    spend: 620.40,
    revenue: 2180.20,
    roas: 3.51,
    cpa: 11.20,
    impressions: 340000,
    clicks: 10800,
    ctr: 3.18,
    purchases: 55,
    profit: 780.40,
    trend: 'up',
  },
  {
    id: 'camp-3',
    name: 'New Launch',
    storeId: 'store-uk',
    storeName: 'UK Store',
    status: 'Active',
    spend: 450.60,
    revenue: 1320.40,
    roas: 2.93,
    cpa: 10.15,
    impressions: 215000,
    clicks: 6900,
    ctr: 3.21,
    purchases: 44,
    profit: 420.10,
    trend: 'stable',
  },
  {
    id: 'camp-4',
    name: 'Retargeting',
    storeId: 'store-us',
    storeName: 'USA Store',
    status: 'Active',
    spend: 300.30,
    revenue: 950.30,
    roas: 3.16,
    cpa: 9.20,
    impressions: 128000,
    clicks: 5100,
    ctr: 3.98,
    purchases: 32,
    profit: 310.20,
    trend: 'up',
  },
  {
    id: 'camp-5',
    name: 'Video Boost',
    storeId: 'store-de',
    storeName: 'Germany Store',
    status: 'Active',
    spend: 169.00,
    revenue: 420.50,
    roas: 2.62,
    cpa: 8.40,
    impressions: 89000,
    clicks: 2900,
    ctr: 3.26,
    purchases: 20,
    profit: 110.40,
    trend: 'down',
  },
  {
    id: 'camp-6',
    name: 'Sunset Lamp Broad Test',
    storeId: 'store-uk',
    storeName: 'UK Store',
    status: 'Paused',
    spend: 210.00,
    revenue: 260.00,
    roas: 1.24,
    cpa: 26.25,
    impressions: 95000,
    clicks: 1800,
    ctr: 1.89,
    purchases: 8,
    profit: -110.00,
    trend: 'down',
  }
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    title: 'TikTok Shop SaaS Suite & Automations',
    category: 'Software',
    amount: 199.00,
    recurrence: 'Monthly',
    storeId: 'all',
    storeName: 'All Stores',
    date: '2024-05-01',
    status: 'Paid',
  },
  {
    id: 'exp-2',
    title: 'Virtual Assistant & TikTok Customer Rep (2 Staff)',
    category: 'Staff',
    amount: 1200.00,
    recurrence: 'Monthly',
    storeId: 'all',
    storeName: 'All Stores',
    date: '2024-05-05',
    status: 'Paid',
  },
  {
    id: 'exp-3',
    title: '3PL Fulfillment Warehouse Storage & Pick-Pack',
    category: 'Warehouse',
    amount: 850.00,
    recurrence: 'Monthly',
    storeId: 'store-us',
    storeName: 'USA Store',
    date: '2024-05-10',
    status: 'Paid',
  },
  {
    id: 'exp-4',
    title: 'TikTok Influencer Samples & Seed Packages (25 units)',
    category: 'Marketing',
    amount: 375.00,
    recurrence: 'One-off',
    storeId: 'store-uk',
    storeName: 'UK Store',
    date: '2024-05-14',
    status: 'Paid',
  },
  {
    id: 'exp-5',
    title: 'Custom Eco Branded Packaging & Poly Mailers',
    category: 'Packaging',
    amount: 450.00,
    recurrence: 'One-off',
    storeId: 'all',
    storeName: 'All Stores',
    date: '2024-05-18',
    status: 'Paid',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Alex Johnson',
    email: 'alex.j@gmail.com',
    country: 'United States',
    totalOrders: 4,
    totalSpent: 168.40,
    netProfit: 98.20,
    cac: 12.45,
    ltv: 168.40,
    lastOrderDate: 'May 23, 2024',
    tier: 'VIP',
  },
  {
    id: 'cust-2',
    name: 'Emily Davis',
    email: 'emily.davis@hotmail.co.uk',
    country: 'United Kingdom',
    totalOrders: 3,
    totalSpent: 114.20,
    netProfit: 66.80,
    cac: 10.15,
    ltv: 114.20,
    lastOrderDate: 'May 23, 2024',
    tier: 'Loyal',
  },
  {
    id: 'cust-3',
    name: 'Michael Brown',
    email: 'm.brown@web.de',
    country: 'Germany',
    totalOrders: 2,
    totalSpent: 88.50,
    netProfit: 41.20,
    cac: 8.40,
    ltv: 88.50,
    lastOrderDate: 'May 23, 2024',
    tier: 'Loyal',
  },
  {
    id: 'cust-4',
    name: 'Sophia Wilson',
    email: 'sophia.w@rogers.ca',
    country: 'Canada',
    totalOrders: 1,
    totalSpent: 22.10,
    netProfit: 13.00,
    cac: 9.20,
    ltv: 22.10,
    lastOrderDate: 'May 23, 2024',
    tier: 'New',
  },
  {
    id: 'cust-5',
    name: 'Chloe Bennett',
    email: 'chloeb@gmail.com',
    country: 'United States',
    totalOrders: 5,
    totalSpent: 245.90,
    netProfit: 142.30,
    cac: 11.20,
    ltv: 245.90,
    lastOrderDate: 'May 23, 2024',
    tier: 'VIP',
  },
];

export const INITIAL_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ins-1',
    type: 'win',
    text: 'Your profit increased by 20.4% compared to last week.',
    detail: 'Revenue grew $3,980.20 while maintaining ad spend efficiency at 3.82x blended ROAS.',
    badge: '+20.4% Net Growth',
  },
  {
    id: 'ins-2',
    type: 'star',
    text: 'Portable Blender is your most profitable product.',
    detail: 'Generated $2,230.40 net profit with a 52.5% margin across USA & UK stores.',
    badge: 'Star Product',
  },
  {
    id: 'ins-3',
    type: 'warning',
    text: "Campaign 'Summer Sale' has high spend but low profit.",
    detail: 'Ad CPA rose to $12.45 on broad target. Recommend narrowing to TikTok Engaged Shoppers.',
    badge: 'Action Needed',
  },
  {
    id: 'ins-4',
    type: 'scale',
    text: 'Consider scaling products with margin > 40%.',
    detail: 'LED Strip Lights and Phone Holder have low ad saturation and >45% profit margins.',
    badge: 'Scale Opportunity',
  },
];

export const INITIAL_TICKETS: CustomerTicket[] = [
  {
    id: 'tkt-1',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.j@icloud.com',
    orderNumber: '#O-24560',
    storeName: 'USA Store',
    subject: 'Where is my order? Ordered 3 days ago',
    category: 'Order Status',
    status: 'Pending AI' as any,
    priority: 'High',
    messages: [
      {
        id: 'msg-1',
        sender: 'customer',
        senderName: 'Sarah Jenkins',
        text: 'Hi, I ordered the portable blender 3 days ago. Can you tell me when it will arrive?',
        timestamp: '10 mins ago',
      },
    ],
    suggestedAiReply: 'Hi Sarah! 👋 Thanks for reaching out. Your order #O-24560 (Portable Blender) was shipped via USPS Priority with tracking number USPS9400111899562230. It is currently in transit and scheduled to arrive on Monday, May 27th. You can track live updates here: https://tools.usps.com. Let us know if you need anything else!',
  },
  {
    id: 'tkt-2',
    customerName: 'David Clark',
    customerEmail: 'david.c@gmail.com',
    orderNumber: '#O-24545',
    storeName: 'UK Store',
    subject: 'How do I clean the portable blender blades safely?',
    category: 'Product Question',
    status: 'AI Responded',
    priority: 'Medium',
    messages: [
      {
        id: 'msg-2',
        sender: 'customer',
        senderName: 'David Clark',
        text: 'Hello, what is the best way to clean the blender without damaging the motor base?',
        timestamp: '2 hours ago',
      },
      {
        id: 'msg-3',
        sender: 'ai',
        senderName: 'Rush AI Assistant',
        text: 'Hi David! ✨ For effortless and safe cleaning: Simply fill the blender halfway with warm water, add a drop of dish soap, secure the lid, and double-press the power button to self-clean for 30 seconds. Rinse thoroughly. The motor base is IPX7 waterproof, but please do not submerge it in boiling water. Happy blending!',
        timestamp: '2 hours ago',
      },
    ],
    suggestedAiReply: '',
  },
  {
    id: 'tkt-3',
    customerName: 'Emma Watson',
    customerEmail: 'emma.w@yahoo.com',
    orderNumber: '#O-24522',
    storeName: 'USA Store',
    subject: 'Item arrived with a broken charging cable',
    category: 'Defect / Damage',
    status: 'Escalated',
    priority: 'High',
    messages: [
      {
        id: 'msg-4',
        sender: 'customer',
        senderName: 'Emma Watson',
        text: 'Hi there, I received my LED lights today but the USB power cable is bent and not turning on. Can I get a replacement?',
        timestamp: '4 hours ago',
      },
      {
        id: 'msg-5',
        sender: 'agent',
        senderName: 'Support Lead (John)',
        text: 'Hi Emma, we are so sorry about that! A replacement USB power adapter and controller has been dispatched today free of charge. Tracking number: USPS9400111899569999.',
        timestamp: '3 hours ago',
      },
    ],
    suggestedAiReply: '',
  },
];

export const PROFIT_TREND_DATA = [
  { date: 'May 17', profit: 1650, revenue: 3200, expenses: 1550 },
  { date: 'May 18', profit: 1980, revenue: 3850, expenses: 1870 },
  { date: 'May 19', profit: 1420, revenue: 2900, expenses: 1480 },
  { date: 'May 20', profit: 2250, revenue: 4300, expenses: 2050 },
  { date: 'May 21', profit: 2680, revenue: 4900, expenses: 2220 },
  { date: 'May 22', profit: 1850, revenue: 3650, expenses: 1800 },
  { date: 'May 23', profit: 1400.20, revenue: 2630.80, expenses: 1230.60 },
];
